### ISSUE TITLE
How to start this project

### ISSUE THREAD

**Issue by t-ide** [istiobyexample-ja/istiobyexample#1]
github-pagesを作りました。試しにCanary Deploymentだけ訳しています  
https://istiobyexample-ja.github.io/istiobyexample/

また，翻訳手順のドラフトをwikiにまとめました。  
typoや訳の第三者チェックのためPull Requestを一応入れてはいますが，
他でチェックができていれば直接master pushでも良い気はします。  
https://github.com/istiobyexample-ja/istiobyexample/wiki

基本的にあとは順次コンテンツを翻訳すれば大丈夫なはずです。
皆さんで並列して翻訳する感じで良いでしょうか?

是非や改善点などあればお願いします。

**Comment by t-ide** [comment]
ちなみに，github-pagesをこちらで立ち上げるために修正のついでに，

- デプロイスクリプトのバグ修正
- markdownのフォーマット統一
- SNS向けリンクプレビュー
- モバイル対応（レスポンシブデザインなど）

を行っています。機をみて本家にもPR投げようと思います。

**Comment by chaspy** [comment]
立ち上げありがとうございます！
ひとまずやってみようと思うので gRPC 私やります。

**Comment by chaspy** [comment]
あ、push できない。いったん fork します。

**Comment by sakajunquality** [comment]
@t-ide @chaspy 
#5 レビューの前に確認していくつか確認しておきたいのですが

- フォーマットとして日本語と英語が混在する場合は英語の前後をスペースでは挟む
- 英語の固有名詞は英語のまま

って感じでいったんいいですかね？

**Comment by sakajunquality** [comment]
あと
canary → カナリア
proxy → プロキシー（伸ばす）
とかで統一する感じっすかね

**Comment by chaspy** [comment]
👍 
Wiki に書いていきたいんで Repository の Write 権限いただけると助かります。

**Comment by sakajunquality** [comment]
@chaspy added

**Comment by chaspy** [comment]
かぶらないようにここで宣言してから訳する感じの Issue つくりました。
https://github.com/istiobyexample-ja/istiobyexample/issues/6

**Comment by sakajunquality** [comment]
すこし最新のアップデートを訳注で追記したくなった
けど一旦全部訳してからでもいいかなーとおもいました

**Comment by t-ide** [comment]
対応ありがとうございます。

> - フォーマットとして日本語と英語が混在する場合は英語の前後をスペースでは挟む
> - 英語の固有名詞は英語のまま
> - canary → カナリア
> - proxy → プロキシー（伸ばす）

これで良いと思います。

**Comment by t-ide** [comment]
翻訳方法に記載漏れがあったので追記しました

> 3. `./data/items.toml`から翻訳したページの`title`を修正する。これがトップページでの記事リンクタイトルとなる

**Comment by t-ide** [comment]
How to startの段階は脱したと思われますので，closeします
