### ISSUE TITLE
Prepare Lint or terms for translation

### ISSUE THREAD

**Issue by chaspy** [istiobyexample-ja/istiobyexample#4]
Istio by example の量がそこまで多くないので必要かどうかは微妙ですが、表記揺れを避けるための Lint だったり、ルールが必要になってきそうです。

レビューを通じて共通認識を形成しつつ。最初は Wiki 等に書いておく、ぐらいでも十分かもしれません。

**Comment by t-ide** [comment]
ありがとうございます。
量も少ないのでまずはwikiの翻訳ルールで良いと思います。何かあったら見直す感じで
