### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by chaspy** [istiobyexample-ja/istiobyexample#6]
コンフリクトしないようにここで宣言してからやる感じでどうでしょうか。直接編集してしまってよいです。

- [x] Traffic Management
  - [x] Canary Deployments @t-ide 
  - [x] gRPC @chaspy #5 
  - [x] Ingress @sakajunquality 
  - [x] External Services @chaspy https://github.com/istiobyexample-ja/istiobyexample/pull/7
  - [x] Load Balancing
  - [x] Locality Load Balanbing
  - [x] Path-Based Routing
  - [x] Modify Resource Headers
  - [x] Retry Logic
  - [x] Fault Injection
  - [x] Database Traffic
  - [x] Traffic Mirroring
  - [x] Monitoring Egress Traffic
  - [x] Multiple Traffic Rules
  - [x] Virtual Machines
- [x] Security
  - [x] Mutual TLS
  - [x] JWT
  - [x] Authorization
  - [x] Secure Ingress
- [x] Observability
  - [x] Bring Your Own Prometheus

**Comment by t-ide** [comment]
全記事の翻訳が終わりましたのでCloseします。皆様ありがとうございました。
