### ISSUE TITLE
How to merge articles already translated

### ISSUE THREAD

**Issue by t-ide** [istiobyexample-ja/istiobyexample#8]
@cyberblack28 さんが既に全記事を翻訳されているそうです。凄いです。

まだ訳していない記事についてはPRを送っていただき、通常の翻訳手順に則って進められればと考えているのですが、既に翻訳を始めている記事はどうしましょう。

**Comment by t-ide** [comment]
また、@cyberblackさんをorgに招待しても良いでしょうか? 現状一番の貢献者ですし、issueで議論するときもそちらの方がスムーズだったりしないかなと（githubに詳しくないので、運用的に間違っていたらご指摘ください）

**Comment by chaspy** [comment]
👍

**Comment by cyberblack28** [comment]
たくさんの人の知見が翻訳に反映されるほうが望ましいので、一つくらいは手順に従ってコントリビュートさせてもらって、もし有志不足があった場合などの利用で構いません。

**Comment by sakajunquality** [comment]
おお！

**Comment by t-ide** [comment]
現状の翻訳状況は #6 の通りで，チェックがついていない項目は手つかずという認識です。
また，既に@cyberblack28さんが翻訳されている記事に関して，今から新規に有志を募るのは勿体ないように思います。

@cyberblack28 
ですので，#6 でチェックがない記事はPRを出していただけると助かります！

（もし，Mergeにあたっての翻訳ルールの違い等による修正作業の負荷が高そうでしたら，cyberblack28さんに負荷が集中しないよう，また別の対策をとれればと思います。）

**Comment by t-ide** [comment]
また，指摘がなさそうですので，@cyberblack28さんをorgにinviteさせていただきます

**Comment by cyberblack28** [comment]
承知しました。

ありがとうございます。

どちらにせよ表記ゆれや和訳するべきかカタカナ英語にするべきかなど色々レビューは必要だと思います。

**Comment by t-ide** [comment]
解決済みですのでCloseします。

IngressとExternal Servicesは既存担当者の方が行い，
それ以外の記事はcyberblack28さんからPRをいただく方針で進めました。
